let n=prompt("Enter your name:")
console.log(n.toLowerCase())
console.log(n.toUpperCase())
console.log(n.indexOf('a'))
console.log(n.lastIndexOf('h'))
console.log(n.charAt(1))
console.log(n.split(' '))
console.log(n.concat("neha"))
console.log(n.slice(2))